Traceback (most recent call last):
  File "C:/Users/satye.MSI/Documents/GitHub/Python-Practice/Automate the boring stuff with Python Programming/Debugging/raise_assert.py", line 45, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "C:/Users/satye.MSI/Documents/GitHub/Python-Practice/Automate the boring stuff with Python Programming/Debugging/raise_assert.py", line 45, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
